---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: do-operator-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: do-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: do-operator-controller-manager
  namespace:  do-operator-system
---