name: Build, Test and Publish

on:
  push:
    branches:
      - main

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.1

      - name: Package Helm chart
        run: |
          export CHART_VERSION="0.1.${{ github.run_number }}"
          export APP_VERSION="0.1.${{ github.run_number }}"
          echo "CHART_VERSION=${CHART_VERSION}"
          echo "APP_VERSION=${APP_VERSION}"
          envsubst < do-operator/Chart.yaml > do-operator/Chart.yaml
          envsubst < do-operator/values.yaml > do-operator/values.yaml
          helm package do-operator --destination repo

      - name: Checkout helm-chart repository
        uses: actions/checkout@v2
        with:
          repository: SupportTools/helm-chart
          path: helm-chart
          token: ${{ secrets.BOT_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.email "github-action@users.noreply.github.com"
          git config --global user.name "GitHub Action"

      - name: Update Helm repository
        run: |
          cp repo/do-operator-*.tgz helm-chart/
          cd helm-chart
          helm repo index . --url https://<YOUR-HELM-CHART-REPOSITORY-URL>/
          git add .
          git commit -m "Update Helm chart for DigitalOcean Operator"
          git push
